apiVersion: v1
kind: Service
metadata:
  name: pritunl-ui
  namespace: pritunl
  annotations:
    {{- toYaml .Values.pritunl.service.annotations | nindent 4 }}
  labels:
{{ include "pritunlUi.labels" . | indent 4 }}
spec:
  type: {{ .Values.pritunlUi.service.type }}
  ports:
  {{ range $index, $port := .Values.pritunlUi.service.ports }}
  - name: {{ $port.name }}
    port: {{ $port.value }}
    targetPort: {{ $port.value }}
    protocol: TCP
  {{ end }}
  selector:
    app: pritunl-ui
