apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pritunl.pvc.name }}
  namespace: pritunl
  labels:
    app: pritunl
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pritunl.pvc.request.storage }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.mongo.pvc.name }}
  namespace: pritunl
  labels:
    app: mongo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mongo.pvc.request.storage }}


