apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "pritunl.fullname" . }}
  labels:
{{ include "pritunl.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "pritunl.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
{{ include "pritunl.labels" . | indent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.pritunl.image.repository }}:{{ .Values.pritunl.image.tag }}"
          imagePullPolicy: {{ .Values.pritunl.image.pullPolicy }}
          env:
            {{ toYaml .Values.pritunl.service.environment | nindent 12 }}
          ports:
          {{ range $index, $port := .Values.pritunl.service.ports }}
            - containerPort: {{ $port.value }}
              protocol: TCP
          {{ end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
{{ include "mongo.labels" . | indent 4 }}
  name: mongo
  namespace: pritunl
spec:
  replicas: 1
  selector:
    matchLabels:
{{ include "mongo.labels" . | indent 6 }}
  template:
    metadata:
      name: mongo
      labels:
{{ include "mongo.labels" . | indent 8 }}
    spec:
      containers:
      - image: "{{ .Values.mongo.image.repository }}:{{ .Values.mongo.image.tag }}"
        name: mongo
        ports:
        - name: mongo
          containerPort: 27017
          hostPort: 27017
        volumeMounts:
          {{ toYaml .Values.mongo.volumeMounts | nindent 10 }}
      volumes:
        {{ toYaml .Values.mongo.volumes | nindent 8 }}
